# Generated by Django 5.2.7 on 2025-11-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_post_latitude_post_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_steps',
            field=models.IntegerField(default=0),
        ),
    ]
