# Generated by Django 5.2.7 on 2025-11-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_total_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default-profile_pic.png', null=True, upload_to='profile_pic/'),
        ),
    ]
